import type {
  Moto,
  Contato,
  Venda,
  Aluguel,
  Proprietario,
} from "./types";

// Mock user usado apenas pelo /api/seed (legacy Mongo seed). O sistema real
// usa o tipo Profile (Supabase) — ver lib/types.ts.
interface MockUser {
  id: string;
  nome: string;
  email: string;
  telefone: string;
  cpf?: string;
  role: "admin" | "vendedor" | "cliente" | "afiliado";
  status: "ativo" | "inativo" | "pendente";
  cidade?: string;
  estado?: string;
  criadoEm: string;
  ultimoAcesso?: string;
  vendasRealizadas?: number;
  comissaoTotal?: number;
}

export const mockProprietarios: Proprietario[] = [
  {
    id: "p1",
    nome: "Roberto Carlos Mendonça",
    cpf: "123.456.789-01",
    rg: "1234567 SSP-CE",
    cnh: "12345678901",
    dataNascimento: "1985-03-15",
    email: "roberto.mendonca@gmail.com",
    telefone: "(88) 99888-7777",
    whatsapp: "(88) 99888-7777",
    cep: "63010-000",
    endereco: "Rua Padre Cícero",
    numero: "1234",
    bairro: "Centro",
    cidade: "Juazeiro do Norte",
    estado: "CE",
    pixTipo: "cpf",
    pixChave: "12345678901",
    criadoEm: "2026-04-10",
    observacoes: "Cliente recorrente, já consignou 2 motos antes.",
  },
  {
    id: "p2",
    nome: "Sandra Maria de Oliveira",
    cpf: "987.654.321-09",
    rg: "9876543 SSP-CE",
    telefone: "(88) 99777-6666",
    email: "sandra.oliveira@hotmail.com",
    cidade: "Crato",
    estado: "CE",
    pixTipo: "telefone",
    pixChave: "(88) 99777-6666",
    criadoEm: "2026-05-02",
  },
  {
    id: "p3",
    nome: "Eduardo Tavares Sousa",
    cpf: "555.666.777-88",
    cnh: "55566677788",
    telefone: "(88) 99555-4444",
    cidade: "Barbalha",
    estado: "CE",
    banco: "Banco do Brasil",
    agencia: "1234-5",
    conta: "12345-6",
    criadoEm: "2026-04-22",
  },
];

export const mockUsers: MockUser[] = [
  {
    id: "u1",
    nome: "Antônio Carlos Silva",
    email: "keu.admin@keumotos.com.br",
    telefone: "(88) 99850-5859",
    cpf: "123.456.789-00",
    role: "admin",
    status: "ativo",
    cidade: "Juazeiro do Norte",
    estado: "CE",
    criadoEm: "2024-01-15",
    ultimoAcesso: "2026-05-11",
  },
  {
    id: "u2",
    nome: "Marcos Vinícius Lima",
    email: "marcos@keumotos.com.br",
    telefone: "(88) 98814-3757",
    role: "vendedor",
    status: "ativo",
    cidade: "Juazeiro do Norte",
    estado: "CE",
    criadoEm: "2024-03-22",
    ultimoAcesso: "2026-05-10",
    vendasRealizadas: 47,
    comissaoTotal: 18500,
  },
  {
    id: "u3",
    nome: "Patrícia Souza Oliveira",
    email: "patricia@keumotos.com.br",
    telefone: "(88) 99123-4567",
    role: "vendedor",
    status: "ativo",
    cidade: "Crato",
    estado: "CE",
    criadoEm: "2024-06-10",
    ultimoAcesso: "2026-05-11",
    vendasRealizadas: 32,
    comissaoTotal: 12300,
  },
  {
    id: "u4",
    nome: "João Pedro Santos",
    email: "joaopedro@gmail.com",
    telefone: "(88) 99654-3210",
    role: "cliente",
    status: "ativo",
    cidade: "Juazeiro do Norte",
    estado: "CE",
    criadoEm: "2025-08-12",
    ultimoAcesso: "2026-05-09",
  },
  {
    id: "u5",
    nome: "Camila Ferreira",
    email: "camila.ferreira@hotmail.com",
    telefone: "(88) 99876-1234",
    role: "cliente",
    status: "ativo",
    cidade: "Barbalha",
    estado: "CE",
    criadoEm: "2026-01-05",
    ultimoAcesso: "2026-05-08",
  },
  {
    id: "u6",
    nome: "Ricardo Almeida",
    email: "ricardo.almeida@gmail.com",
    telefone: "(88) 99234-5678",
    role: "cliente",
    status: "pendente",
    cidade: "Juazeiro do Norte",
    estado: "CE",
    criadoEm: "2026-05-08",
  },
];

export const mockMotos: Moto[] = [
  {
    id: "m1",
    marca: "Honda",
    modelo: "CG 160 Titan",
    versao: "Start",
    anoFabricacao: 2023,
    anoModelo: 2024,
    cor: "Vermelha",
    placa: "ABC-1D23",
    chassi: "9C2KC2200PR123456",
    renavam: "01234567890",
    numeroMotor: "KC22E1234567",
    cilindrada: 160,
    combustivel: "flex",
    cambio: "manual",
    partida: "eletrica",
    km: 8500,
    potencia: "14.7 cv",
    valorFipe: 14800,
    valorCompra: 11500,
    valorAnunciado: 15200,
    valorMinimo: 13800,
    comissao: 500,
    tipo: "venda",
    status: "disponivel",
    destaque: true,
    fotos: [],
    descricao: "Moto em excelente estado, único dono, todas revisões em dia.",
    dataEntrada: "2026-03-15",
    vendedorResponsavel: "Marcos Vinícius Lima",
    setor: "multimarcas",
    origem: "comprada",
    proprietarioId: "p1",
    proprietarioNome: "Roberto Carlos Mendonça",
    compra: {
      valorPago: 11500,
      formaPagamento: "pix",
      dataAquisicao: "2026-03-15",
      numeroNotaFiscal: "NF-2025-0314",
    },
  },
  {
    id: "m2",
    marca: "Yamaha",
    modelo: "Fazer 250",
    versao: "ABS",
    anoFabricacao: 2024,
    anoModelo: 2024,
    cor: "Preta",
    placa: "DEF-4G56",
    chassi: "9C6RG431KS0789012",
    renavam: "12345678901",
    cilindrada: 250,
    combustivel: "flex",
    cambio: "manual",
    partida: "eletrica",
    km: 3200,
    potencia: "21.5 cv",
    valorFipe: 22500,
    valorCompra: 0,
    valorAnunciado: 23800,
    valorMinimo: 21500,
    comissao: 800,
    tipo: "venda",
    status: "disponivel",
    destaque: true,
    fotos: [],
    dataEntrada: "2026-04-02",
    vendedorResponsavel: "Patrícia Souza Oliveira",
    setor: "multimarcas",
    origem: "repasse",
    proprietarioId: "p2",
    proprietarioNome: "Sandra Maria de Oliveira",
    repasse: {
      valorCombinadoDono: 20500,
      tipoComissao: "percentual",
      comissaoPercentual: 7,
      prazoConsignacao: 60,
      dataInicioConsignacao: "2026-04-02",
      contratoAssinado: true,
      observacoesAcordo: "Cliente aceita oferta acima de R$ 21.500.",
    },
  },
  {
    id: "m3",
    marca: "Honda",
    modelo: "Biz 125",
    versao: "ES",
    anoFabricacao: 2022,
    anoModelo: 2023,
    cor: "Branca",
    placa: "GHI-7J89",
    cilindrada: 125,
    combustivel: "flex",
    cambio: "semi-automatico",
    partida: "eletrica",
    km: 15200,
    valorFipe: 11200,
    valorCompra: 8800,
    valorAnunciado: 11500,
    valorMinimo: 10200,
    comissao: 400,
    valorDiaria: 80,
    valorSemanal: 480,
    valorMensal: 1800,
    caucao: 500,
    tipo: "ambos",
    status: "disponivel",
    fotos: [],
    dataEntrada: "2026-02-20",
    setor: "loca",
    origem: "propria",
  },
  {
    id: "m4",
    marca: "Honda",
    modelo: "PCX 160",
    versao: "DLX",
    anoFabricacao: 2024,
    anoModelo: 2025,
    cor: "Cinza",
    cilindrada: 160,
    combustivel: "gasolina",
    cambio: "cvt",
    partida: "eletrica",
    km: 1200,
    potencia: "15.8 cv",
    valorFipe: 19500,
    valorCompra: 16800,
    valorAnunciado: 20200,
    valorMinimo: 18800,
    comissao: 600,
    tipo: "venda",
    status: "reservada",
    destaque: true,
    fotos: [],
    dataEntrada: "2026-04-15",
    vendedorResponsavel: "Marcos Vinícius Lima",
    setor: "multimarcas",
    origem: "comprada",
  },
  {
    id: "m5",
    marca: "Yamaha",
    modelo: "Factor 150",
    versao: "ED",
    anoFabricacao: 2023,
    anoModelo: 2023,
    cor: "Azul",
    cilindrada: 150,
    combustivel: "flex",
    cambio: "manual",
    partida: "eletrica",
    km: 22000,
    valorFipe: 13800,
    valorCompra: 10500,
    valorAnunciado: 14200,
    valorMinimo: 12800,
    valorDiaria: 70,
    valorSemanal: 420,
    valorMensal: 1500,
    caucao: 400,
    tipo: "ambos",
    status: "alugada",
    fotos: [],
    dataEntrada: "2025-12-10",
    setor: "loca",
    origem: "propria",
  },
  {
    id: "m6",
    marca: "Kawasaki",
    modelo: "Ninja 400",
    versao: "ABS",
    anoFabricacao: 2024,
    anoModelo: 2024,
    cor: "Verde",
    cilindrada: 400,
    combustivel: "gasolina",
    cambio: "manual",
    partida: "eletrica",
    km: 5800,
    potencia: "49 cv",
    valorFipe: 38500,
    valorCompra: 32000,
    valorAnunciado: 39800,
    valorMinimo: 36500,
    comissao: 1500,
    tipo: "venda",
    status: "disponivel",
    destaque: true,
    fotos: [],
    dataEntrada: "2026-03-28",
    vendedorResponsavel: "Patrícia Souza Oliveira",
    setor: "multimarcas",
    origem: "comprada",
  },
  {
    id: "m7",
    marca: "Honda",
    modelo: "CB 500F",
    anoFabricacao: 2023,
    anoModelo: 2024,
    cor: "Preta",
    cilindrada: 471,
    combustivel: "gasolina",
    cambio: "manual",
    partida: "eletrica",
    km: 9800,
    potencia: "48 cv",
    valorFipe: 35200,
    valorCompra: 29500,
    valorAnunciado: 36800,
    valorMinimo: 33800,
    comissao: 1200,
    tipo: "venda",
    status: "disponivel",
    fotos: [],
    dataEntrada: "2026-04-10",
    setor: "multimarcas",
    origem: "comprada",
  },
  {
    id: "m8",
    marca: "Honda",
    modelo: "Pop 110i",
    anoFabricacao: 2022,
    anoModelo: 2022,
    cor: "Vermelha",
    cilindrada: 110,
    combustivel: "flex",
    cambio: "semi-automatico",
    partida: "eletrica",
    km: 18500,
    valorFipe: 9200,
    valorCompra: 7200,
    valorAnunciado: 9500,
    valorMinimo: 8500,
    valorDiaria: 60,
    valorSemanal: 360,
    valorMensal: 1200,
    caucao: 300,
    tipo: "aluguel",
    status: "disponivel",
    fotos: [],
    dataEntrada: "2025-11-05",
    setor: "loca",
    origem: "propria",
  },
];

export const mockContatos: Contato[] = [
  {
    id: "c1",
    nome: "Fernando Costa",
    telefone: "(88) 99888-7766",
    email: "fernando@gmail.com",
    origem: "instagram",
    interesse: "compra",
    motoInteresse: "Honda CG 160 Titan",
    status: "em-atendimento",
    vendedorResponsavel: "Marcos Vinícius Lima",
    criadoEm: "2026-05-09",
    ultimoContato: "2026-05-10",
  },
  {
    id: "c2",
    nome: "Lúcia Mendes",
    telefone: "(88) 99777-6655",
    origem: "whatsapp",
    interesse: "aluguel",
    motoInteresse: "Honda Biz 125",
    status: "novo",
    criadoEm: "2026-05-11",
  },
  {
    id: "c3",
    nome: "Paulo Henrique",
    telefone: "(88) 99666-5544",
    email: "paulo.h@hotmail.com",
    origem: "site",
    interesse: "troca",
    observacoes: "Possui Honda CG 150 Fan 2018, quer trocar por Fazer 250",
    status: "em-atendimento",
    vendedorResponsavel: "Patrícia Souza Oliveira",
    criadoEm: "2026-05-07",
    ultimoContato: "2026-05-09",
  },
  {
    id: "c4",
    nome: "Beatriz Cardoso",
    telefone: "(88) 99555-4433",
    origem: "presencial",
    interesse: "pecas",
    observacoes: "Procura kit relação para CG 160",
    status: "convertido",
    criadoEm: "2026-05-05",
  },
  {
    id: "c5",
    nome: "Marcelo Tavares",
    telefone: "(88) 99444-3322",
    email: "marcelot@gmail.com",
    origem: "indicacao",
    interesse: "compra",
    motoInteresse: "Kawasaki Ninja 400",
    status: "em-atendimento",
    vendedorResponsavel: "Patrícia Souza Oliveira",
    criadoEm: "2026-05-08",
    ultimoContato: "2026-05-10",
  },
];

export const mockVendas: Venda[] = [
  {
    id: "v1",
    motoId: "m99",
    motoModelo: "Honda CG 160 Start 2023",
    clienteId: "u4",
    clienteNome: "João Pedro Santos",
    vendedorId: "u2",
    vendedorNome: "Marcos Vinícius Lima",
    valorVendido: 14500,
    formaPagamento: "financiado",
    parcelas: 36,
    comissao: 500,
    data: "2026-04-22",
    status: "concluida",
  },
  {
    id: "v2",
    motoId: "m98",
    motoModelo: "Yamaha Fazer 150 2022",
    clienteId: "u5",
    clienteNome: "Camila Ferreira",
    vendedorId: "u3",
    vendedorNome: "Patrícia Souza Oliveira",
    valorVendido: 12800,
    formaPagamento: "a-vista",
    comissao: 450,
    data: "2026-05-03",
    status: "concluida",
  },
  {
    id: "v3",
    motoId: "m4",
    motoModelo: "Honda PCX 160 DLX 2025",
    clienteId: "u4",
    clienteNome: "João Pedro Santos",
    vendedorId: "u2",
    vendedorNome: "Marcos Vinícius Lima",
    valorVendido: 19800,
    formaPagamento: "financiado",
    parcelas: 48,
    comissao: 600,
    data: "2026-05-10",
    status: "pendente",
  },
];

export const mockAlugueis: Aluguel[] = [
  {
    id: "a1",
    motoId: "m5",
    motoModelo: "Yamaha Factor 150 2023",
    clienteId: "u5",
    clienteNome: "Camila Ferreira",
    vendedorId: "u3",
    dataInicio: "2026-05-01",
    dataFim: "2026-06-01",
    valorTotal: 1500,
    caucao: 400,
    status: "ativo",
    km_inicial: 22000,
  },
  {
    id: "a2",
    motoId: "m99",
    motoModelo: "Honda Biz 125 2021",
    clienteId: "u4",
    clienteNome: "João Pedro Santos",
    vendedorId: "u2",
    dataInicio: "2026-04-15",
    dataFim: "2026-04-22",
    valorTotal: 480,
    caucao: 500,
    status: "concluido",
    km_inicial: 14500,
    km_final: 14820,
  },
];
